<?php

	#################################################################
	# Podcast Generator
	# http://podcastgen.sourceforge.net
	# developed by Alberto Betella
	#
	# Config.php file created automatically - v.1.4


	$podcastgen_version = "1.4"; // Version

	$scriptlang = "en";

	$url = "http://media.mvgals.net/ot/ot_podcast/"; // Complete URL of the script (Trailing slash REQUIRED)

	$absoluteurl = "/opt/media/www/ot/ot_podcast/"; // Absolute path on the server (Trailing slash REQUIRED)

	$theme_path = "themes/ot/";

	$username = "ot";

	$userpassword = "7d3c8a790acc9a40cf214345c5f57515";

	$max_upload_form_size = "104857600"; //e.g.: "30000000" (about 30MB)

	$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

	$img_dir = "images/";  // (Trailing slash required). Set chmod 755

	$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

	$max_recent = 10; // How many file to show in the home page

	$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

	$episodeperpage = 10;

	$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")

	$streamingplayercolor = "grey";

	$dateformat = "d-m-Y"; // d-m-Y OR m-d-Y OR Y-m-d 

	$freebox = "no"; // enable freely customizable box

	$enablehelphints = "yes";

	$enablepgnewsinadmin = "yes";

	$strictfilenamepolicy = "yes"; // strictly rename files (just characters A to Z and numbers) 

	$categoriesenabled = "no";


	###################
	# XML Feed elements
	# The followings specifications will be included in your podcast "feed.xml" file.


	$podcast_title = "The Opulent Temple Podcasts";

	$podcast_subtitle = "A podcast with a purpose...";

	$podcast_description = "The Opulent Temple started as a large scale art &amp; music theme camp at the annual Burning Man arts festival that takes place in the Black Rock Desert of Nevada, celebrated the week before Labor Day. We throw nightly parties showcasing underground world class electronic dance music in a setting of art and creation we've made ourselves. The effort is self generated by the tribe and no one gets paid to create our production. On the contrary, key members put much of their own time, effort, and sometimes money all year around into bringing it back every year. Our community and fund raising events are based in San Francisco and though our production is associated with the BM event, we will be taking it to other settings. 

The Opulent Temple Podcast shines the spotlight on the resident djs of the OT family and features mixes exploring the diverse musical flavors of underground electronica, including electro, progressive, techno, breaks, tech funk, indie/nu-disco, trance, and a dash of dubstep-glitch. This show consists of Opulent Temple residents and special guests. You can learn more about Opulent Temple, our djs, music, events, community happenings, and everything else in between, by visiting us online at Opulent Temple dot org.";

	$author_name = "The Opulent Temple Crew"; 

	$author_email = "podcasts@opulenttemple.org"; 

	$itunes_category[0] = "Music"; // iTunes categories (mainCategory:subcategory)
	$itunes_category[1] = "Arts";
	$itunes_category[2] = "Society&Culture";

	$link = $url."?p=episode&amp;name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

	$feed_language = "en"; // Language used in the XML feed (can differ from the script language).

	$copyright = "The Opulent Temple crew or their respective guests"; // Copyright notice

	$feed_encoding = "utf-8"; // Feed Encoding (e.g. "iso-8859-1", "utf-8"). UTF-8 is strongly suggested

	$explicit_podcast = "no"; //does your podcast contain explicit language? ("yes", "no" or "clean")

	// END OF CONFIGURATION

	?>
